const Classifier = Object.freeze({
    COMPLEXO: {
        label: "Complexo",
        keywords: [
            "[bug]",
            "[reclamação]",
            "erro",
            "não funciona",
            "não consigo",
            "não aparece",
            "problema",
            "exception",
            "falha",
            "não abre",
            "não roda",
            "não carrega",
            "travando",
            "crash",
            "bugado",
            "não compila",
            "não imprime",
            "não executa",
            "message:",
            "traceback",
            "stack overflow",
            "arquitetura",
            "performance",
            "melhorar",
            "estratégia",
            "gestão",
            "otimizar",
            "melhor forma",
            "qual a melhor",
            "boas práticas",
            "padrão de projeto",
            "design pattern",
            "estrutura",
            "pipeline",
            "ambiente",
            "sobrecarga",
            "comportamento estranho",
            "variáveis de ambiente",
            "testes automatizados",
            "deploy",
            "banco de dados",
            "api rest",
            "persistência",
            "thread",
            "assíncrono",
            "async",
            "await",
            "kernel",
            "hook",
            "encapsulamento",
            "parâmetro",
            "modularização",
            "tentei fazer",
            "extra",
            "melhoria",
            "otimizar",
        ],
    },

    FEEDBACK: {
        label: "Feedback",
        keywords: [
            "[projeto]",
            "[Projeto]",
            "meu projeto",
            "minha resolução",
            "minha solução",
            "meu codigo",
            "meu exercício",
            "meu exercicio",
            "meu portfólio",
            "portifólio",
            "projeto final",
            "projeto concluído",
            "quero feedback",
            "avaliação",
            "dêem feedback",
            "meu site",
            "meu app",
            "desafios finais",
            "desafio - hora da pratica",
            "resolução",
            "desafio",
        ],
    },

    FACIL: {
        label: "Fácil",
        keywords: [
            "dúvida",
            "como faço",
            "o que é",
            "para que serve",
            "iniciante",
            "primeiros passos",
            "ajuda",
            "não entendi",
            "explicação",
            "passo a passo",
            "erro simples",
            "como começo",
            "aprendendo agora",
            "sou novo",
            "primeira vez",
        ],
    },
});

module.exports = {
    Classifier,
};
